packages:
  - "apps/*"
  - "packages/*"
  # packages/ui + packages/tsconfig are symlinks created by scripts/link-shared-packages.sh
allowBuilds:
  sharp: false
minimumReleaseAgeExclude:
  - puppeteer-core@25.4.0 || 25.5.0
  - '@puppeteer/browsers@3.1.0'
