# Source: https://betterstack.com/community/guides/database-platforms/index/
# Original language: ini
# Normalized: ini
# Block index: 8

[label /etc/systemd/system/pocketbase.service]
[Unit]
Description = PocketBase Server

[Service]
Type = simple
User = root
ExecStart = /usr/local/bin/pocketbase serve --http="0.0.0.0:8090" --dir="/opt/pocketbase_data/"
Restart = always
RestartSec = 5s

[Install]
WantedBy = multi-user.target