# Source: https://betterstack.com/community/guides/scaling-php/laravel-docker/
# Original language: ini
# Normalized: ini
# Block index: 22

[label php/local.ini]
upload_max_filesize=40M
post_max_size=40M