# Source: https://betterstack.com/community/guides/monitoring/prometheus-exporter/
# Original language: conf
# Normalized: conf
# Block index: 3

[label nginx.conf]
. . .

http {
    . . .

[highlight]
    server {
        listen 80;
        server_name localhost nginx;

        location /stub_status {
          stub_status;
        }
    }
[/highlight]

    include /etc/nginx/conf.d/*.conf;
}