# Source: https://betterstack.com/community/guides/monitoring/prometheus-relabeling/
# Original language: yaml
# Normalized: yaml
# Block index: 16

[label prometheus.yml]
relabel_configs:
  - action: labeldrop
    regex: job