# Source: https://betterstack.com/community/guides/monitoring/java-prometheus/
# Original language: yaml
# Normalized: yaml
# Block index: 3

[label prometheus.yml]
global:
 scrape_interval: 10s

scrape_configs:
 - job_name: spring-app
   static_configs:
     - targets:
         - app:8080