# Source: https://betterstack.com/community/guides/monitoring/prometheus-relabeling/
# Original language: yaml
# Normalized: yaml
# Block index: 14

[label prometheus.yml]
metric_relabel_configs:
  - source_labels: [__name__]
    regex: go_.* # drop all metrics prefixed with `go_`
    action: drop