# Source: https://betterstack.com/community/guides/scaling-docker/docker-compose-vs-kubernetes/
# Original language: yaml
# Normalized: yaml
# Block index: 28

[label dev-patch.yaml]
apiVersion: apps/v1
kind: Deployment
metadata:
 name: web-app
spec:
 template:
   spec:
     containers:
     - name: nginx
       env:
       - name: DEBUG
         value: "true"