# Source: https://betterstack.com/community/guides/scaling-docker/kubernetes-getting-started/
# Original language: yaml
# Normalized: yaml
# Block index: 36

[label hello-app-service.yaml]
apiVersion: v1
kind: Service
metadata:
  name: hello-app-service
spec:
  selector:
    app: hello-app
  ports:
  - port: 80
    targetPort: 8080
  type: NodePort