# Source: https://betterstack.com/community/guides/web-servers/index/
# Original language: yaml
# Normalized: yaml
# Block index: 46

[label docker-compose.yml]
version: '3'

name: caddy-tutorial

services:
  caddy:
    container_name: caddy
    image: caddy
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - caddy-config:/config
      - caddy-data:/data
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./dist:/usr/share/caddy
  vector:
    container_name: vector
    image: timberio/vector:0.34.0-alpine
    restart: always
    volumes:
      - ./vector.yaml:/etc/vector/vector.yaml
      - /var/run/docker.sock:/var/run/docker.sock:ro
[highlight]
  backend:
    container_name: backend
    image: node:20-alpine
    restart: always
    working_dir: /home/node/app
    volumes:
      - ./backend:/home/node/app
    command: "npm start"
[/highlight]

volumes:
  caddy-config:
  caddy-data: